Add support for deleting symlinks
Symlinks have to be treated specially because `shutil.rmtree()` does not work
on directories:

    $ ln -s some_directory symlink
    $ python3
    >>> import shutil
    >>> shutil.rmtree('symlink')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3/shutil.py", line 736, in rmtree
        onerror(os.path.islink, path, sys.exc_info())
      File "/usr/lib/python3/shutil.py", line 734, in rmtree
        raise OSError("Cannot call rmtree on a symbolic link")
    OSError: Cannot call rmtree on a symbolic link