Fix run of flake8 in Travis CI for Python 3.2.
We need to use an older version when installing flake8 under Python 3.2 as it
fails with the following error when using the latest version:

    File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/flake8/options/config.py", line 63
      if isinstance(files, (str, type(u''))):
                                      ^
    SyntaxError: invalid syntax

With 3.4.1, it should run fine.